portefaix/portefaix-hub

.github/workflows/chart-test.yml
README.md

Fix: Documentation Artifact Hub

---

charts/thanos-mixin/README.md

Update: documentation

---

charts/thanos-mixin/Chart.yaml
charts/thanos-mixin/README.md

Thanos v0.18.0 : Chart and application versions

---

charts/loki-mixin/Chart.yaml
charts/loki-mixin/README.md
charts/promtail-mixin/Chart.yaml
charts/promtail-mixin/README.md
charts/promtail-mixin/templates/rules.yaml
hack/mixins.py

Loki and Promtail to v2.2.0

---

Makefile

Portefaix policies v0.3.0

---

Makefile

Portefaix OPA policies v0.4.0

---

.github/workflows/draft-labels.yml

Manage Draft PR and state labels

---

charts/speedtest-exporter/Chart.yaml
charts/speedtest-exporter/README.md
charts/speedtest-exporter/templates/_helpers.tpl

[speedtest-exporter] Kubernetes recommanded labels

---

charts/kube-state-metrics-mixin/Chart.yaml
charts/kube-state-metrics-mixin/README.md
charts/kube-state-metrics-mixin/templates/alerts.yaml

kube-state-metrics v2.0.0

---

charts/thanos-mixin/Chart.yaml
charts/thanos-mixin/README.md
charts/thanos-mixin/dashboards/bucket_replicate.json
charts/thanos-mixin/dashboards/compact.json
charts/thanos-mixin/dashboards/overview.json
charts/thanos-mixin/dashboards/query.json
charts/thanos-mixin/dashboards/receive.json
charts/thanos-mixin/dashboards/rule.json
charts/thanos-mixin/dashboards/sidecar.json
charts/thanos-mixin/dashboards/store.json
charts/thanos-mixin/templates/_helpers.tpl
charts/thanos-mixin/templates/alerts.yaml
charts/thanos-mixin/templates/configmap-bucket_replicate.yaml
charts/thanos-mixin/templates/configmap-compact.yaml
charts/thanos-mixin/templates/configmap-overview.yaml
charts/thanos-mixin/templates/configmap-query.yaml
charts/thanos-mixin/templates/configmap-receive.yaml
charts/thanos-mixin/templates/configmap-rule.yaml
charts/thanos-mixin/templates/configmap-sidecar.yaml
charts/thanos-mixin/templates/configmap-store.yaml
charts/thanos-mixin/templates/rules.yaml
hack/mixins.py
hack/thanos-mixin.tpl
hack/thanos-mixin_dashboard.tpl

Thanos mixin v0.21.0 with Grafana dashboards

---

charts/promtail-mixin/Chart.yaml
charts/promtail-mixin/README.md
charts/promtail-mixin/templates/_helpers.tpl
charts/promtail-mixin/templates/alerts.yaml
charts/promtail-mixin/templates/rules.yaml

Promtail mixin with dashboards

---

charts/prometheus-operator-mixin/Chart.yaml
charts/prometheus-operator-mixin/README.md
charts/prometheus-operator-mixin/templates/_helpers.tpl
charts/prometheus-operator-mixin/templates/alerts.yaml

prometheus-operator-mixin v0.48.0

---

charts/prometheus-mixin/Chart.yaml
charts/prometheus-mixin/README.md
charts/prometheus-mixin/templates/_helpers.tpl
charts/prometheus-mixin/templates/alerts.yaml

Prometheus mixin with dashboards

---

charts/prometheus-mixin/Chart.yaml
charts/prometheus-mixin/README.md
charts/prometheus-mixin/dashboards/prometheus-remote-write.json
charts/prometheus-mixin/dashboards/prometheus.json
charts/prometheus-mixin/templates/configmap-prometheus-remote-write.yaml
charts/prometheus-mixin/templates/configmap-prometheus.yaml

Prometheus mixin alerts and dashboards

---

charts/kubernetes-mixin/Chart.yaml
charts/kubernetes-mixin/README.md
charts/kubernetes-mixin/templates/_helpers.tpl
charts/kubernetes-mixin/templates/alerts.yaml
charts/kubernetes-mixin/templates/configmap-apiserver.yaml
charts/kubernetes-mixin/templates/configmap-cluster-total.yaml
charts/kubernetes-mixin/templates/configmap-controller-manager.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-cluster.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-namespace.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-node.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-pod.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-workload.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-workloads-namespace.yaml
charts/kubernetes-mixin/templates/configmap-kubelet.yaml
charts/kubernetes-mixin/templates/configmap-namespace-by-pod.yaml
charts/kubernetes-mixin/templates/configmap-namespace-by-workload.yaml
charts/kubernetes-mixin/templates/configmap-persistentvolumesusage.yaml
charts/kubernetes-mixin/templates/configmap-pod-total.yaml
charts/kubernetes-mixin/templates/configmap-proxy.yaml
charts/kubernetes-mixin/templates/configmap-scheduler.yaml
charts/kubernetes-mixin/templates/configmap-statefulset.yaml
charts/kubernetes-mixin/templates/configmap-workload-total.yaml
charts/kubernetes-mixin/templates/rules.yaml
charts/kubernetes-mixin/values.yaml
hack/mixins/mixin_dashboard.tpl
hack/mixins/mixin_prom.tpl

[kubernetes-mixin] Refactoring labels

---

charts/kubernetes-mixin/Chart.yaml
charts/kubernetes-mixin/README.md
charts/kubernetes-mixin/templates/configmap-apiserver.yaml
charts/kubernetes-mixin/templates/configmap-cluster-total.yaml
charts/kubernetes-mixin/templates/configmap-controller-manager.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-cluster.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-namespace.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-node.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-pod.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-workload.yaml
charts/kubernetes-mixin/templates/configmap-k8s-resources-workloads-namespace.yaml
charts/kubernetes-mixin/templates/configmap-kubelet.yaml
charts/kubernetes-mixin/templates/configmap-namespace-by-pod.yaml
charts/kubernetes-mixin/templates/configmap-namespace-by-workload.yaml
charts/kubernetes-mixin/templates/configmap-persistentvolumesusage.yaml
charts/kubernetes-mixin/templates/configmap-pod-total.yaml
charts/kubernetes-mixin/templates/configmap-proxy.yaml
charts/kubernetes-mixin/templates/configmap-scheduler.yaml
charts/kubernetes-mixin/templates/configmap-statefulset.yaml
charts/kubernetes-mixin/templates/configmap-workload-total.yaml
hack/mixins/mixin_dashboard.tpl

Grafana label and annotation

---

charts/kubernetes-mixin/Chart.yaml
charts/kubernetes-mixin/README.md
charts/kubernetes-mixin/dashboards/apiserver.json
charts/kubernetes-mixin/dashboards/cluster-total.json
charts/kubernetes-mixin/dashboards/controller-manager.json
charts/kubernetes-mixin/dashboards/k8s-resources-cluster.json
charts/kubernetes-mixin/dashboards/k8s-resources-namespace.json
charts/kubernetes-mixin/dashboards/k8s-resources-node.json
charts/kubernetes-mixin/dashboards/k8s-resources-pod.json
charts/kubernetes-mixin/dashboards/k8s-resources-workload.json
charts/kubernetes-mixin/dashboards/k8s-resources-workloads-namespace.json
charts/kubernetes-mixin/dashboards/kubelet.json
charts/kubernetes-mixin/dashboards/namespace-by-pod.json
charts/kubernetes-mixin/dashboards/namespace-by-workload.json
charts/kubernetes-mixin/dashboards/persistentvolumesusage.json
charts/kubernetes-mixin/dashboards/pod-total.json
charts/kubernetes-mixin/dashboards/proxy.json
charts/kubernetes-mixin/dashboards/scheduler.json
charts/kubernetes-mixin/dashboards/statefulset.json
charts/kubernetes-mixin/dashboards/workload-total.json
charts/kubernetes-mixin/templates/alerts.yaml
charts/kubernetes-mixin/templates/rules.yaml

[kubernetes-mixin] Refactoring cadvisor using monitoring-mixins v0.7.0

---

charts/linkerd-edge-mixin/Chart.yaml
charts/linkerd-edge-mixin/README.md

Linkerd Edge mixin chart name

---

charts/linkerd-stable-mixin/Chart.yaml
charts/linkerd-stable-mixin/README.md

Linkerd logo

---

charts/loki-mixin/Chart.yaml
charts/loki-mixin/README.md
charts/loki-mixin/templates/alerts.yaml
charts/loki-mixin/templates/configmap-loki-chunks.yaml
charts/loki-mixin/templates/configmap-loki-logs.yaml
charts/loki-mixin/templates/configmap-loki-operational.yaml
charts/loki-mixin/templates/configmap-loki-reads.yaml
charts/loki-mixin/templates/configmap-loki-writes.yaml
charts/loki-mixin/templates/rules.yaml
hack/mixins.py

Grafana folder and name

---

charts/kube-state-metrics-mixin/Chart.yaml
charts/kube-state-metrics-mixin/README.md
charts/kube-state-metrics-mixin/templates/alerts.yaml

Labels for kube-state-metrics mixin

---

charts/prometheus-operator-mixin/Chart.yaml
charts/prometheus-operator-mixin/README.md
charts/prometheus-operator-mixin/templates/alerts.yaml

Update: labels for prometheus-operator-mixin

---

charts/alertmanager-mixin/Chart.yaml
charts/alertmanager-mixin/README.md
charts/alertmanager-mixin/templates/alerts.yaml

Alertmanager mixin labels

---

charts/grafana-mixin/Chart.yaml
charts/grafana-mixin/README.md
charts/grafana-mixin/dashboards/grafana-overview.json
charts/grafana-mixin/templates/alerts.yaml
charts/grafana-mixin/templates/configmap-grafana-overview.yaml
charts/grafana-mixin/templates/rules.yaml

Grafana mixin labels

---

charts/portefaix-kyverno/Chart.yaml
charts/portefaix-kyverno/README.md
charts/portefaix-kyverno/templates/policy-C0001.yaml
charts/portefaix-kyverno/templates/policy-C0002.yaml
charts/portefaix-kyverno/templates/policy-C0003.yaml
charts/portefaix-kyverno/templates/policy-C0004.yaml
charts/portefaix-kyverno/templates/policy-C0005.yaml
charts/portefaix-kyverno/templates/policy-C0006.yaml
charts/portefaix-kyverno/templates/policy-C0008.yaml
charts/portefaix-kyverno/templates/policy-M0001.yaml
charts/portefaix-kyverno/templates/policy-M0002.yaml
charts/portefaix-kyverno/templates/policy-M0003.yaml
charts/portefaix-kyverno/templates/policy-P0002.yaml
charts/portefaix-kyverno/templates/policy-P0003.yaml
charts/portefaix-kyverno/templates/policy-P0004.yaml
charts/portefaix-kyverno/templates/policy-P0005.yaml
hack/policies.py

Bump Kyverno policies to v0.7.0

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml
.github/workflows/draft-labels copy.yml
.github/workflows/renovate.yml
.github/workflows/size.yaml

New Github Actions workflows

---

charts/kubernetes-mixin/Chart.yaml
charts/kubernetes-mixin/README.md
charts/kubernetes-mixin/templates/NOTES.txt

- Changelog
- How check PrometheusRule and configmap which contains Grafana dashboards
- fixes #

[kubernetes-mixin] Kubernetes mixin 0.6.0

---

charts/promtail-mixin/Changelog.md
charts/promtail-mixin/Chart.yaml
charts/promtail-mixin/README.md
charts/promtail-mixin/templates/NOTES.txt

- promtail-mixin v2.3.0 from monitoring-mixins v0.10.0
- changelog and documentation
- fixes #

[promtail-mixin] Promtail mixin v2.3.0

---

.github/config_repos
.github/workflows/chart-kubeval.yml
.github/workflows/chart-release.yml
.github/workflows/chart-test.yml
.github/workflows/chart-validate.yml
.github/workflows/prow-labels.yml
.github/workflows/prow-lgtm-merge.yml
.github/workflows/prow-lgtm-pull.yml
.github/workflows/prow.yml
.github/workflows/release-drafter.yml

Refactoring Github Actions
- fixes #

CICD refactoring

---

charts/secrets-store-csi-driver-provider-aws/Chart.yaml
charts/secrets-store-csi-driver-provider-aws/README.md
charts/secrets-store-csi-driver-provider-aws/values.yaml

[secrets-store-csi-driver-provider-aws] Set default resources

---

charts/secrets-store-csi-driver-provider-gcp/Chart.yaml
charts/secrets-store-csi-driver-provider-gcp/README.md
charts/secrets-store-csi-driver-provider-gcp/values.yaml

[secrets-store-csi-driver-provider-gcp] Bump csi-secret-store-provider-gcp to v1.0.0

---

charts/secrets-store-csi-driver-provider-aws/Chart.yaml
charts/secrets-store-csi-driver-provider-aws/README.md
charts/secrets-store-csi-driver-provider-aws/values.yaml

[secrets-store-csi-driver-provider-aws] Do not set default resources

---

charts/secrets-store-csi-driver-provider-aws/README.md

Chart is deprecated.
- fixes #

[secrets-store-csi-driver-provider-aws] Deprecated message

---

charts/crossplane-aws-factory/Chart.yaml
charts/crossplane-aws-factory/README.md
charts/crossplane-aws-factory/templates/eks.yaml
charts/crossplane-aws-factory/templates/iam-eks.yaml
charts/crossplane-aws-factory/templates/sg.yaml
charts/crossplane-aws-factory/templates/vpc.yaml
charts/crossplane-gcp-factory/.helmignore
charts/crossplane-gcp-factory/Chart.yaml
charts/crossplane-gcp-factory/README.md
charts/crossplane-gcp-factory/templates/NOTES.txt
charts/crossplane-gcp-factory/templates/_helpers.tpl
charts/crossplane-gcp-factory/templates/buckets.yaml
charts/crossplane-gcp-factory/templates/cloudsql.yaml
charts/crossplane-gcp-factory/templates/firewall.yaml
charts/crossplane-gcp-factory/templates/gcp-config.yaml
charts/crossplane-gcp-factory/templates/gcp-controller-config.yaml
charts/crossplane-gcp-factory/templates/gcp-provider.yaml
charts/crossplane-gcp-factory/templates/gke.yaml
charts/crossplane-gcp-factory/templates/iam.yaml
charts/crossplane-gcp-factory/templates/memorystore.yaml
charts/crossplane-gcp-factory/templates/network.yaml
charts/crossplane-gcp-factory/templates/pubsub.yaml
charts/crossplane-gcp-factory/templates/subnetwork.yaml
charts/crossplane-gcp-factory/values.yaml
charts/secrets-store-csi-driver-provider-aws/Chart.yaml
charts/secrets-store-csi-driver-provider-aws/README.md

[crossplane-gcp-factory] GCP Factory using Crossplane

---

.pre-commit-config.yaml
charts/crossplane-gcp-factory/Chart.yaml
charts/crossplane-gcp-factory/README.md
charts/crossplane-gcp-factory/templates/pubsub.yaml
charts/crossplane-gcp-factory/values.yaml

[crossplane-gcp-factory] Multiple PubSub topics and subscriptions

---

.github/workflows/chart-release.yml

Helm Github Action to v1.1 and Helm v3.7.1

---

charts/crossplane-aws-factory/Chart.yaml
charts/crossplane-aws-factory/README.md
charts/crossplane-aws-factory/values.yaml
charts/thanos-mixin/Chart.yaml
charts/thanos-mixin/README.md

Crossplane v0.15.1 and AWS provider v0.21.2

---

.github/workflows/chart-release.yml
charts/alertmanager-mixin/Chart.yaml
charts/alertmanager-mixin/README.md

Integrate the [Sigstore](https://github.com/sigstore/) ecosystem

Sigstore support

---

charts/alertmanager-mixin/Chart.yaml

Fix: changelog for Alertmanager mixin chart

---

.github/workflows/chart-release.yml

Fix: GPG and Helm

---

charts/crossplane-aws-factory/Chart.yaml

Helm and GPG for crossplane-aws-factory

---

charts/crossplane-gcp-factory/Chart.yaml

Helm and GPG for crossplane-gcp-factory

---

charts/fluxcd-mixin/Chart.yaml

Helm and GPG for fluxcd-mixin

---

charts/grafana-mixin/Chart.yaml

Helm and GPG for grafana-mixin

---

charts/kube-state-metrics-mixin/Chart.yaml

Helm and GPG for kube-state-metrics-mixin

---

charts/linkerd-edge-mixin/Chart.yaml
charts/linkerd-stable-mixin/Chart.yaml

Helm and GPG for Linkerd mixin

---

charts/kubernetes-mixin/Chart.yaml

Helm and GPG for kubernetes-mixin

---

charts/loki-mixin/Chart.yaml
charts/promtail-mixin/Chart.yaml

Helm and GPG for Loki and Promtail mixins

---

charts/node-exporter-mixin/Chart.yaml
charts/prometheus-mixin/Chart.yaml
charts/prometheus-operator-mixin/Chart.yaml

Helm and GPG for Prometheus and co

---

charts/speedtest-exporter/Chart.yaml

Helm and GPG for Speedtest Exporter

---

charts/kubernetes-mixin/Chart.yaml
charts/kubernetes-mixin/README.md
charts/kubernetes-mixin/templates/alerts.yaml
charts/kubernetes-mixin/templates/rules.yaml

[kubernetes-mixin] typo

---

charts/speedtest-exporter/Chart.yaml
charts/speedtest-exporter/README.md
charts/speedtest-exporter/templates/_helpers.tpl
charts/speedtest-exporter/templates/deployment.yaml
charts/speedtest-exporter/templates/service.yaml
charts/speedtest-exporter/templates/serviceaccount.yaml
charts/speedtest-exporter/templates/servicemonitor.yaml
charts/speedtest-exporter/values.yaml

[speedtest-exporter] Refactoring Kubernetes labels

---

.github/helm-docs.sh

Helm-docs v1.7.0

---

charts/bbox-exporter/Chart.yaml
charts/bbox-exporter/README.md
charts/bbox-exporter/templates/deployment.yaml
charts/bbox-exporter/templates/secret.yaml
charts/bbox-exporter/values.yaml

[prometheus-bbox-exporter] Refactoring secret

---

charts/portefaix-kyverno/templates/policy-N0001.yaml
hack/policies.py

Update to Portefaix Policies `v0.8.0`
- fixes #

Portefaix policies v0.8.0

---

charts/portefaix-kubewarden/Chart.yaml
charts/portefaix-kubewarden/README.md
charts/portefaix-kubewarden/templates/NOTES.txt

Fixed typos in portefaix-kubewarden chart.
Bumped chart version as requested by PR.
- None

[portefaix-kubewarden] Fix typos in portefaix-kubewarden chart

---

charts/portefaix-kubewarden/Chart.yaml
charts/portefaix-kubewarden/README.md

[portefaix-kubewarden] fix: Typo in portefaix-kubewarden Chart.yaml

---

charts/bbox-exporter/Chart.yaml
charts/freebox-exporter/Chart.yaml

Fix: ArtifactHub changelogs

---

charts/tempo-mixin/Chart.yaml
charts/tempo-mixin/README.md
charts/tempo-mixin/templates/configmap-dashboards.yaml

When there are more than 1 dashboard we need to have a YAML document delimiter per file
- fixes #

[tempo-mixin] Fix Helm loop for dashboards

---

charts/prometheus-operator-mixin/Chart.yaml

[prometheus-operator-mixin] Fix version

---

charts/mimir-mixin/Chart.yaml
charts/mimir-mixin/README.md
charts/mimir-mixin/templates/_helpers.tpl

[mimir-mixin] Additional labels and annotations

---

charts/podtato-head/Chart.yaml
charts/podtato-head/README.md
charts/podtato-head/templates/_helpers.tpl
charts/podtato-head/templates/deployment-entry.yaml
charts/podtato-head/templates/deployment-hat.yaml
charts/podtato-head/templates/deployment-left-arm.yaml
charts/podtato-head/templates/deployment-left-leg.yaml
charts/podtato-head/templates/deployment-right-arm.yaml
charts/podtato-head/templates/deployment-right-leg.yaml
charts/podtato-head/templates/service-entry.yaml
charts/podtato-head/templates/service-hat.yaml
charts/podtato-head/templates/service-left-arm.yaml
charts/podtato-head/templates/service-left-leg.yaml
charts/podtato-head/templates/service-right-arm.yaml
charts/podtato-head/templates/service-right-leg.yaml

[podtato-head] Labels for KLT

---

charts/podtato-head/Chart.yaml
charts/podtato-head/README.md
charts/podtato-head/templates/ingress.yaml

[podtato-head] Ingress API version

---

.github/workflows/chart-manual.yml
charts/ack-factory/Chart.yaml
charts/ack-factory/README.md
charts/ack-factory/values.yaml

[ack-factory] Additional labels

---

charts/ack-factory/Chart.yaml
charts/ack-factory/README.md
charts/ack-factory/values.yaml

[ack-factory] EKS v1.25

---

charts/crossplane-aws-factory/Chart.yaml
charts/crossplane-aws-factory/values.yaml

[crossplane-aws-factory] Additional labels and annotations

---

charts/alertmanager-mixin/Chart.yaml
charts/alertmanager-mixin/README.md
charts/alertmanager-mixin/dashboards/overview.json
charts/alertmanager-mixin/templates/alerts.yaml

[alertmanager-mixin] Refactoring monitoring labels

---

charts/pyroscope-mixin/Chart.yaml

[pyroscope-mixin] Fix: chart number

---

charts/portefaix-kyverno/Chart.yaml

[portefaix-kyverno] Fix: chart version

---

charts/tempo-mixin/Chart.yaml
charts/tempo-mixin/templates/_helpers.tpl

Invalid YAML indentation when we set the `additionalLabels` entry.
- fixes #

[tempo-mixin] Additional labels YAML indentation

---

charts/grafana-agent-flow-mixin/Chart.yaml
charts/tempo-mixin/Chart.yaml

Fix: Grafana Agent Flow and Tempo sources

---

charts/cloudflare-tunnel/Chart.yaml
charts/cloudflare-tunnel/README.md
charts/cloudflare-tunnel/templates/configmap.yaml
charts/cloudflare-tunnel/templates/deployment.yaml
charts/cloudflare-tunnel/templates/service.yaml
charts/cloudflare-tunnel/values.yaml

[cloudflare-tunnel] Metrics port and ServiceMonitor resource #546

---

charts/cloudflare-tunnel/values.yaml

[cloudflare-tunnel]: specify Cloudflared Docker image

---

charts/portefaix-kubewarden/templates/policy-M0002.yaml

[portefaix-kubewarden]: clean policies

---

charts/ack-factory/Chart.yaml
charts/ack-factory/templates/_helpers.tpl
charts/ack-factory/templates/ecr.yaml
charts/ack-factory/templates/eip.yaml
charts/ack-factory/templates/eks.yaml
charts/ack-factory/templates/gateways.yaml
charts/ack-factory/templates/iam.yaml
charts/ack-factory/templates/s3.yaml
charts/ack-factory/templates/sg.yaml
charts/ack-factory/templates/subnets.yaml
charts/ack-factory/templates/vpc.yaml

[ack-factory]: cleanup Kubernetes labels

---

charts/quickwit/.helmignore
charts/quickwit/Chart.yaml
charts/quickwit/templates/NOTES.txt
charts/quickwit/templates/_helpers.tpl
charts/quickwit/templates/configmap-bootstrap.yaml
charts/quickwit/templates/configmap.yaml
charts/quickwit/templates/control-plane-deployment.yaml
charts/quickwit/templates/indexer-pdb.yaml
charts/quickwit/templates/indexer-statefulset.yaml
charts/quickwit/templates/ingress.yaml
charts/quickwit/templates/janitor-deployment.yaml
charts/quickwit/templates/job-create-indices.yaml
charts/quickwit/templates/job-create-sources.yaml
charts/quickwit/templates/metastore-deployment.yaml
charts/quickwit/templates/prometheusrule.yaml
charts/quickwit/templates/searcher-pdb.yaml
charts/quickwit/templates/searcher-statefulset.yaml
charts/quickwit/templates/secret.yaml
charts/quickwit/templates/service.yaml
charts/quickwit/templates/serviceaccount.yaml
charts/quickwit/templates/servicemonitor.yaml
charts/quickwit/values.yaml

New chart to deploy [Quickwit](https://quickwit.io/)
- https://github.com/quickwit-oss/helm-charts/pull/63
- https://github.com/quickwit-oss/helm-charts/pull/78
- https://github.com/quickwit-oss/helm-charts/pull/80

[quickwit] New chart

---

charts/quickwit/Chart.yaml
charts/quickwit/templates/serviceaccount.yaml

[quickwit] Cleanup additional labels

---

.gitignore
charts/gateway-api-crds/Chart.yaml
charts/gateway-api-crds/charts/crds/Chart.yaml
charts/gateway-api-crds/charts/crds/templates/gateway.networking.k8s.io_gatewayclasses.yaml
charts/gateway-api-crds/charts/crds/templates/gateway.networking.k8s.io_gateways.yaml
charts/gateway-api-crds/charts/crds/templates/gateway.networking.k8s.io_httproutes.yaml
charts/gateway-api-crds/charts/crds/templates/gateway.networking.k8s.io_referencegrants.yaml

[gateway-api-crds] Add CRDs

---

charts/sealed-secrets-crds/Chart.yaml
charts/sealed-secrets-crds/README.md

[sealed-secrets-crds] New charts

---

charts/pyroscope-mixin/Chart.yaml
charts/pyroscope-mixin/README.md
charts/pyroscope-mixin/templates/_helpers.tpl
charts/pyroscope-mixin/templates/configmap-dashboards.yaml
charts/pyroscope-mixin/templates/rules.yaml
charts/pyroscope-mixin/values.yaml

feat(pyroscope): Enable Grafana Operator

---

charts/tempo-mixin/Chart.yaml
charts/tempo-mixin/templates/configmap-dashboards.yaml

fix(tempo-mixin): ConfigMap naming

---

charts/pyroscope-mixin/Chart.yaml
charts/pyroscope-mixin/templates/configmap-dashboards.yaml

fix(pyroscope-mixin): ConfigMap naming

---

charts/loki-mixin/Chart.yaml

feat(loki-mixin): bump chart version

---

charts/portefaix-cel/Chart.yaml
charts/portefaix-cel/README.md
charts/portefaix-cel/templates/policy-C0001.yaml
charts/portefaix-cel/templates/policy-C0002.yaml
charts/portefaix-cel/templates/policy-C0003.yaml
charts/portefaix-cel/templates/policy-C0008.yaml
charts/portefaix-cel/templates/policy-M0001.yaml
charts/portefaix-cel/templates/policy-M0002.yaml
charts/portefaix-cel/templates/policy-M0003.yaml
charts/portefaix-cel/templates/policy-N0001.yaml

…dmissionPolicyBinding
- fixes #

[portefaix-cel] v1 for ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBinding

---

charts/cloudflare-tunnel/Chart.yaml

fix(cloudflared): chart version

---

charts/trivy-operator-crds/Chart.yaml
charts/trivy-operator-crds/charts/crds/templates/aquasecurity.github.io_clustersbomreports.yaml
charts/trivy-operator-crds/hack/update_crds.sh

[trivy-operator-crds] Missing CRD

---

.github/renovate.json5
charts/gateway-api-crds/Chart.yaml
charts/grafana-operator-crds/Chart.yaml
charts/sealed-secrets-crds/Chart.yaml
charts/traefik-crds/Chart.yaml
charts/traefik-hub-crds/Chart.yaml
charts/trivy-operator-crds/Chart.yaml

Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com

feat(crds): setup Renovate

---

charts/pyrra-service-levels/Chart.yaml
charts/pyrra-service-levels/templates/NOTES.txt

[pyrra-service-levels]: Add some notes

---

charts/portefaix-cel/Chart.yaml
charts/portefaix-cel/charts/crds/Chart.yaml
charts/portefaix-cel/charts/crds/templates/policy.portefaix.xyz_registryconfiguration.yaml
charts/portefaix-cel/templates/_helpers.tpl
charts/portefaix-cel/templates/policy-C0001.yaml
charts/portefaix-cel/templates/policy-C0002.yaml
charts/portefaix-cel/templates/policy-C0003.yaml
charts/portefaix-cel/templates/policy-C0008.yaml
charts/portefaix-cel/templates/policy-M0001.yaml
charts/portefaix-cel/templates/policy-M0002.yaml
charts/portefaix-cel/templates/policy-N0001.yaml
charts/portefaix-cel/templates/policy-P0001.yaml
charts/portefaix-cel/values.yaml

[portefaix-cel] P0001 Policy to validate registries

---

charts/pyrra-service-levels/Chart.yaml
charts/pyrra-service-levels/templates/slo-bool.yaml
charts/pyrra-service-levels/templates/slo-latency.yaml
charts/pyrra-service-levels/templates/slo-ratio.yaml
charts/pyrra-service-levels/values.yaml

[pyrra] Naming resources

---

charts/fake/Chart.yaml

feat(fake): test
